name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version from version.txt
        id: get_version
        run: echo "version=v$(cat version.txt)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build binary
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --icon=assets/icons/nyan.ico src/nyan_bounce.py
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            pyinstaller --onefile --icon=assets/icons/nyan.icns src/nyan_bounce.py
          else
            pyinstaller --onefile --icon=assets/icons/nyan.png src/nyan_bounce.py
          fi
        shell: bash

      - name: Rename artifact
        run: |
          mkdir dist_upload
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/nyan_bounce.exe dist_upload/nyan_bounce-${{ env.version }}-win.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/nyan_bounce dist_upload/nyan_bounce-${{ env.version }}-mac
          else
            mv dist/nyan_bounce dist_upload/nyan_bounce-${{ env.version }}-linux
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ env.version }}-${{ matrix.os }}
          path: dist_upload/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: |
            binaries-${{ env.version }}-ubuntu-latest
            binaries-${{ env.version }}-windows-latest
            binaries-${{ env.version }}-macos-latest
          path: release_files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          name: Release ${{ env.version }}
          files: release_files/*
