name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version from version.txt
        id: get_version
        shell: bash
        run: |
          VERSION="v$(cat version.txt)"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build binary
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --icon=assets/icons/nyan.ico src/nyan_bounce.py
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            pyinstaller --onefile --icon=assets/icons/nyan.icns src/nyan_bounce.py
          else
            pyinstaller --onefile --icon=assets/icons/nyan.png src/nyan_bounce.py
          fi

      - name: Rename artifact
        shell: bash
        run: |
          mkdir -p dist_upload
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/nyan_bounce.exe dist_upload/nyan_bounce-${{ env.version }}-win.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/nyan_bounce dist_upload/nyan_bounce-${{ env.version }}-mac
          else
            mv dist/nyan_bounce dist_upload/nyan_bounce-${{ env.version }}-linux
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist_upload/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get version from build job
        run: echo "version=${{ needs.build.outputs.version }}" >> $GITHUB_ENV

      - name: Download all artifacts from matrix
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: release_files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          name: Release ${{ env.version }}
          files: release_files/*


