#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
nyan_bounce.py
Nyan Cat rebondit sur le bureau avec traînée cubique continue et correctement orientée.
Musique et GIF inclus pour PyInstaller.
"""

import sys
import os
import shutil
import tempfile
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QApplication, QLabel, QWidget
import pygame  # pour la musique

# ------------------------
# Fonctions pour PyInstaller
# ------------------------
def resource_path(relative_path):
    """Retourne le chemin correct vers les assets, même dans un .exe PyInstaller"""
    if hasattr(sys, "_MEIPASS"):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)

# ------------------------
# Initialisation musique
# ------------------------
pygame.mixer.init()

music_src = resource_path("assets/nyan.mp3")
tmp_dir = tempfile.gettempdir()
music_tmp = os.path.join(tmp_dir, "nyan.mp3")
shutil.copyfile(music_src, music_tmp)

pygame.mixer.music.load(music_tmp)
pygame.mixer.music.play(-1)  # boucle infinie

# ------------------------
# Initialisation application PyQt
# ------------------------
app = QApplication(sys.argv)

# Fenêtre principale
window = QWidget()
window.setWindowTitle("Nyan Bounce")
window.setGeometry(100, 100, 400, 400)

# Label pour le GIF
gif_label = QLabel(window)
gif_path = resource_path("assets/nyan.gif")
pixmap = QPixmap(gif_path)
gif_label.setPixmap(pixmap)
gif_label.setAlignment(Qt.AlignCenter)
gif_label.resize(pixmap.width(), pixmap.height())

window.show()

# ------------------------
# Timer pour mouvements (exemple simple)
# ------------------------
def move_label():
    x = (gif_label.x() + 5) % window.width()
    y = (gif_label.y() + 5) % window.height()
    gif_label.move(x, y)

timer = QTimer()
timer.timeout.connect(move_label)
timer.start(50)  # 20 FPS

# ------------------------
# Lancement de l'application
# ------------------------
try:
    sys.exit(app.exec_())
finally:
    pygame.mixer.music.stop()


